spring:
    application:
        name: "Notes App"
    datasource:
        url: jdbc:postgresql://localhost:5432/notesapp
        username: postgres
        password: YcB80dLX&fO641cC
        driver-class-name: org.postgresql.Driver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
server:
    servlet:
        context-path: /api
